[tool.poetry]
name = "workshop-ao-vivo-airflow"
version = "0.1.0"
description = ""
authors = ["lvgalvaofilho <lvgalvaofilho@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
apache-airflow = "^2.8.3"
loguru = "^0.7.2"
streamlit = "^1.32.2"
requests = "^2.31.0"
python-dotenv = "^1.0.1"
pydantic = "^2.6.4"
apache-airflow-providers-postgres = "^5.10.2"
astro-sdk-python = {extras = ["duckdb"], version = "^1.8.0"}
airflow-provider-duckdb = "^0.2.0"
duckdb = "^0.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
